server {
  listen 80;
  server_name localhost;

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    # Эта строчка — магия для Single Page Application (SPA)
    # Если файл не найден, она отдает index.html, а React Router уже разбирается с путем
    try_files $uri $uri/ /index.html;
  }
}
