FROM python:3.12.3-slim

ARG SAFETY_API_KEY=${SAFETY_API_KEY}

ENV DJANGO_ENV=${DJANGO_ENV} \
    SAFETY_API_KEY=${SAFETY_API_KEY} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_ROOT_USER_ACTION=ignore \
    POETRY_VERSION=1.6.1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_HOME='/usr/local'

SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

RUN apt-get update && apt-get install -y wget gnupg lsb-release
RUN echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-client-16

RUN apt-get update && apt-get upgrade -y \
  && apt-get install --no-install-recommends -y \
    bash \
    brotli \
    build-essential \
    curl \
    gettext \
    git \
    libpq-dev \
    wait-for-it \
  && curl -sSL 'https://install.python-poetry.org' | python - \
  && poetry --version

COPY ./poetry.lock ./pyproject.toml ./manage.py ./start.sh /code/
WORKDIR /code
RUN chmod +x start.sh
ENV PATH=$PATH:/usr/local/python3/bin

RUN echo "$DJANGO_ENV" \
    && poetry version \
    && poetry run pip install -U pip \
    && POETRY_CACHE_DIR='/var/cache/pypoetry' poetry install

COPY ./static /code/static