# Generated by Django 5.2.4 on 2025-07-26 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя/ФИО')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('phone', models.CharField(max_length=50, verbose_name='Контактный номер')),
                ('request_text', models.TextField(verbose_name='Запрос')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заявки')),
                ('sent_to_amocrm', models.BooleanField(default=False, verbose_name='Отправлено в amoCRM')),
                ('sent_to_telegram', models.BooleanField(default=False, verbose_name='Отправлено в Telegram')),
                ('amocrm_response', models.TextField(blank=True, null=True, verbose_name='Ответ amoCRM')),
                ('telegram_response', models.TextField(blank=True, null=True, verbose_name='Ответ Telegram')),
            ],
        ),
    ]
