# Generated by Django 5.2.4 on 2025-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='request_text',
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_method',
            field=models.CharField(default='phone', max_length=20, verbose_name='Удобный способ связи'),
        ),
        migrations.AddField(
            model_name='lead',
            name='privacy_policy_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности'),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.JSONField(default=list, verbose_name='Выбранные услуги'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='application_created_220e22_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sent_to_amocrm'], name='application_sent_to_fb264a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sent_to_telegram'], name='application_sent_to_d2523b_idx'),
        ),
    ]
